




resolver_dict={ 'sawlive.tv': 'sawlive',
            'streamking.co': 'streamking',
            'streamking.cc': 'streamking',
            'castalba.tv' : 'castalba',
            'p2pcast.tv' : 'p2pcast',
            'finecast.tv' : 'finecast',
            'filmon.com' : 'filmon',
            'miplayer.net' : 'miplayer',
            'lshstream.com' : 'lshunter',
            'cdn.lshstream.com' : 'lshunter',
            'castamp.com' : 'castamp',
            'yocast.tv': 'yocast',
            'streamlive.to' : 'streamlive',
            '04stream.com' : 'o4stream',
            'ustream.tv' : 'ustream' ,#not implemented
            'playwire.com' : 'playwire',
            'leton.tv' : 'leton',
            'yotv.co' : 'yotv',
            'hdcast.me' : 'hdcast',
            'zerocast.tv' : 'zerocast',
            'castup.tv' : 'castup',
            'mybeststream.xyz' :'mybeststream',#not implemented
            'sunhd.info' : 'dinozap',
            'youtube.com' : 'youtube',
            'livestream.com' : 'livestream',
            'new.livestream.com' : 'livestream',
            'privatestream.tv' : 'privatestream',
            'airq.tv' : 'airq',
            'aliez.me' : 'aliez',
            'emb.aliez.me' : 'aliez',
            'emb.aliez.tv' : 'aliez',
            'p3g.tv' : 'p3g',
            'liveflashplayer.net' : 'liveflashplayer',
            'laola1.tv' : 'laola1',
            'ehftv.com' : 'ehftv',
            'zoomtv.me' : 'zoomtv',#not implemented
            'iguide.to' : 'iguide',
            'letgo.tv' : 'letgo',
            'streamup.com' : 'streamup',
            'cast3d.tv' : 'cast3d',
            'xvtr.pw' : 'dinozap',
            'turbocast.tv' : 'turbocast', #not implemented
            'direct-stream.org' : 'directstream',
            'pxstream.tv' : 'pxstream',
            'pushpublish.tv' : 'publishpublish',
            'embeducaster.com' : 'ucaster',
            'rocktv.co' : 'rocktv',
            'embedezcast.com' : 'ezcast',
            'micast.tv' : 'micast',
            'openlive.org' : 'openlive',
            'sostart.org' : 'sostart',
            'hdmyt.info' : 'dinozap',
            'hqstream.tv' : 'hqstream',
            'tutelehd.com' : 'tutele',
            'janjua.tv' : 'janjuaf',
            'abcast.net' : 'abcast',
            'castfree.me' : 'castfree',
            'playerapp1.pw' : 'dinozap','playerapp2.pw' : 'dinozap','dinostream.pw' : 'dinozap','dinozap.info'  : 'dinozap','livesports15.ucoz.com' : 'dinozap','dinozap.pw' : 'dinozap','playerhd1.pw' : 'dinozap','playerhd2.pw' : 'dinozap',
            'tv.verdirectotv.org' : 'dinozap','hdcastream.info' : 'dinozap','serverhd.eu' : 'dinozap','sitenow.me' : 'dinozap','sstream.pw' : 'dinozap','uefahd.com' : 'dinozap',
            'boxlivetv.eu' : 'dinozap',
            'weplayer.pw':'dinozap',
            'streamcasttv.biz':'streamcasttv',
            'vaughnlive.tv' : 'vaughnlive',
            'hdcast.org' : 'hdcast_org',
            'ustream.tv' : 'ustream',
            'cast4u.tv' : 'cast4u',
            'youtu.be' : 'youtube',
            'direct-stream.org' : 'directstream',
            'veetle.com' : 'veetle',
            'tvope.com' : 'tvope',
            'static.castto.me' :  'castto',
            'castasap.pw' : 'castasap',
            'flashlive.pw' : 'castasap',
            'castflash.pw' : 'castasap',
            'fastflash.pw' : 'castasap'
              }
